# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fitGPBAU <- function(y, X, prior, starting, tuning, mod_param, mcmc_settings) {
    .Call(`_spds_fitGPBAU`, y, X, prior, starting, tuning, mod_param, mcmc_settings)
}

predGPBAU2 <- function(y, X, post_sams, mod_param, nreport) {
    .Call(`_spds_predGPBAU2`, y, X, post_sams, mod_param, nreport)
}

predGPBAU3 <- function(y, X, post_sams, mod_param, nreport) {
    .Call(`_spds_predGPBAU3`, y, X, post_sams, mod_param, nreport)
}

expCorr <- function(distmat, phi) {
    .Call(`_spds_expCorr`, distmat, phi)
}

